### ISSUE TITLE
How to install as service❓

### ISSUE THREAD

**Issue by zbuh** [johnDorian/rockbin#18]
I installed and tested, and its working fine.
but does not autostart after a reboot.

I'm using it on a S5 with valetudo 2021.12.1

**Comment by alexeysitka** [comment]
Just fix permissions of autostarting script with:
chmod +x /etc/init/S12Rockbin

**Comment by johnDorian** [comment]
@alexeysitka Would you be able to provide me the output of the following command after you ran `chmod`. 

`ls -ltrh /sbin/initctl/S12Rockbin` 

I can fix up the configure step once I know the working file permissions.

**Comment by alexeysitka** [comment]
I have no such file "/sbin/initctl/S12Rockbin". It is enough presence of S12Rockbin with "X" permission inside /etc/init for proper auto-starting. Mine has:

[root@rockrobo ~]# ls -ltrh /etc/init/S12Rockbin
-rwxr-xr-x    1 root     root        2.0K Jan 23 17:46 /etc/init/S12Rockbin

Also I suggest to update your README.md

Firstly necessary to move bin file
mv rockbin /usr/local/bin/rockbin
and fix its permission
chmod +x /usr/local/bin/rockbin

Then try to configure and run serve for testing purpose
/usr/local/bin/rockbin configure
/usr/local/bin/rockbin serve --log_level debug

Otherwise running configure from root's home produces wrong binary path for start inside /etc/init/S12Rockbin (from root home).
