### ISSUE TITLE
Move all variables into a config file 

### ISSUE THREAD

**Issue by johnDorian** [johnDorian/rockbin#7]
Currently all the configuration settings are set using environment variables or arguments to the binary. It would make the configuration settings and the upstart/init scripts easier to maintain if this was all kept in a separate config file.

**Comment by Sennevds** [comment]
Did you had a certain library in mind to use for the config parsing? I did some searching and found the following https://github.com/spf13/viper but this is maybe a little bit too extended for what's needed

**Comment by johnDorian** [comment]
Yeah that’s the library I was going to use. I didn’t use it in the beginning because as you you point out it seems a little excessive. 

However if we move the parameters into a config file, using cobra and viper would be the easiest approach and this is what I had in mind for this ticket.

**Comment by Sennevds** [comment]
Okay tested your new cli. chmod +x should be executed before launching configure otherwise you'll get an error: Permission denied.
I've accidentally copied rockbin executable to /mnt/data and then copied the the binary to the /root folder (so the rockbin binary still existed in /mnt/data) then when I tried to configure rockbin at the end I got an error: open /mnt/data/rockbin/rockbin.yaml: not a directory
Otherwise it looks like it's working

**Comment by johnDorian** [comment]
Great thanks for the feedback. I'll try and update the readme and create a release.

**Comment by Sennevds** [comment]
Aha tested a bit more and you use sudo in the S12Rockbin file but sudo isn't a recognized command

**Comment by johnDorian** [comment]
Good catch. Do you think the latest push would fix that? https://github.com/johnDorian/rockbin/commit/5fd9edc596f48226a86f0187fb7e078fb1f6f34f#diff-bb9ec668a1f106b15b2fa4e998537f152b77b024ecbc1c7ddcb74ecdd29cfedb
